### ISSUE TITLE
Less than needs to be \lt in XML

### ISSUE THREAD

**Issue by davidfarmer** [ymittal/asciimath#1]
The expression
```
5 < 6
```
is valid LaTeX, but including that in a PreTeXt document gives an error
because the less-than character is special in XML.

So unlike standard AsciiMath, in PXT the conversion needs to
write it as
```
5 \lt 6
```

**Comment by ymittal** [comment]
Good catch. bc52460fa610fda4d83c724c7da52d9594a5964f fixes it.
